class Constants {
  static List<String> getVehicleMakesList() {
    return [
      'Toyota',
      'Honda',
      'Nissan',
      'Mazda',
      'Ford',
      'Chevrolet',
      'Hyundai',
      'Kia',
      'BMW',
      'Mercedes-Benz',
      'Audi',
      'Volkswagen',
      'Volvo',
      'Subaru',
      'Mitsubishi',
      'Suzuki',
      'Lexus',
      'Infiniti',
      'Porsche',
      'Jaguar',
      'Land Rover',
      'Acura',
      'Mini',
      'Smart',
      'Dodge',
      'Chrysler',
      'Jeep',
      'Ram',
      'Fiat',
      'Alfa Romeo',
      'Lamborghini',
      'Maserati',
      'Bentley',
      'Rolls-Royce',
      'Genesis',
      'Buick',
      'Cadillac',
      'Lincoln',
      'GMC',
      'Aston Martin',
      'Tesla',
      'Other',
    ];
  }

  static Map<String, List<String>> getVehicleModels() {
    Map<String, List<String>> models = {
      'Toyota': [
        '4Runner',
        'Avalon',
        'C-HR',
        'Camry',
        'Corolla',
        'Highlander',
        'Land Cruiser',
        'Mirai',
        'Prius',
        'Rav4',
        'Sequoia',
        'Sienna',
        'Supra',
        'Tacoma',
        'Tundra',
        'Venza',
        'Yaris'
      ],
      'Honda': [
        'Accord',
        'Civic',
        'Clarity',
        'CR-V',
        'Fit',
        'HR-V',
        'Insight',
        'Odyssey',
        'Passport',
        'Pilot',
        'Ridgeline'
      ],
      'Nissan': [
        '370Z',
        'Altima',
        'Armada',
        'Frontier',
        'GT-R',
        'Kicks',
        'Leaf',
        'Maxima',
        'Murano',
        'NV Cargo',
        'NV Passenger',
        'NV200',
        'Pathfinder',
        'Rogue',
        'Rogue Sport',
        'Sentra',
        'Titan',
        'Versa'
      ],
      'Mazda': [
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-9',
        'MX-5 Miata',
        'Mazda3',
        'Mazda6'
      ],
      'Ford': [
        'Bronco',
        'EcoSport',
        'Edge',
        'Escape',
        'Expedition',
        'Explorer',
        'F-150',
        'F-250',
        'F-350',
        'Fiesta',
        'Flex',
        'Focus',
        'Fusion',
        'Mustang',
        'Ranger',
        'Transit Connect'
      ],
      'Chevrolet': [
        'Blazer',
        'Bolt',
        'Camaro',
        'Colorado',
        'Equinox',
        'Express',
        'Impala',
        'Malibu',
        'Silverado 1500',
        'Silverado 2500HD',
        'Silverado 3500HD',
        'Spark',
        'Suburban',
        'Tahoe',
        'Trailblazer',
        'Traverse',
        'Trax'
      ],
      'Hyundai': [
        'Accent',
        'Elantra',
        'Ioniq',
        'Kona',
        'NEXO',
        'Palisade',
        'Santa Fe',
        'Sonata',
        'Tucson',
        'Veloster'
      ],
      'Kia': [
        'Forte',
        'K5',
        'Niro',
        'Optima',
        'Rio',
        'Sedona',
        'Seltos',
        'Sorento',
        'Soul',
        'Sportage',
        'Stinger',
        'Telluride'
      ],
      'BMW': [
        '2 Series',
        '3 Series',
        '4 Series',
        '5 Series',
        '7 Series',
        '8 Series',
        'i3',
        'i8',
        'M2',
        'M3',
        'M4',
        'M5',
        'M8',
        'X1',
        'X2',
        'X3',
        'X4',
        'X5',
        'X6',
        'X7',
        'Z4'
      ],
      'Mercedes-Benz': [
        'A-Class',
        'C-Class',
        'CLA-Class',
        'CLS-Class',
        'E-Class',
        'G-Class',
        'GLA-Class',
        'GLB-Class',
        'GLC-Class',
        'GLE-Class',
        'GLS-Class',
        'S-Class',
        'SL-Class',
        'SLS AMG',
        'Sprinter'
      ],
      'Audi': [
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'e-tron',
        'Q3',
        'Q5',
        'Q7',
        'Q8',
        'R8',
        'RS 3'
      ],
      'Volkswagen': [
        'Arteon',
        'Atlas',
        'Beetle',
        'Golf',
        'Jetta',
        'Passat',
        'Tiguan'
      ],
      'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
      'Subaru': [
        'Ascent',
        'BRZ',
        'Crosstrek',
        'Forester',
        'Impreza',
        'Legacy',
        'Outback',
        'WRX'
      ],
      'Mitsubishi': ['Eclipse Cross', 'Mirage', 'Outlander', 'Outlander PHEV'],
      'Suzuki': ['Equator'],
      'Lexus': [
        'ES',
        'GS',
        'GX',
        'IS',
        'LC',
        'LS',
        'LX',
        'NX',
        'RC',
        'RX',
        'UX'
      ],
      'Infiniti': ['Q50', 'Q60', 'QX30', 'QX50', 'QX60', 'QX80'],
      'Porsche': [
        '718 Boxster',
        '718 Cayman',
        '911',
        'Cayenne',
        'Macan',
        'Panamera',
        'Taycan'
      ],
      'Jaguar': ['E-PACE', 'F-PACE', 'F-TYPE', 'I-PACE', 'XE', 'XF', 'XJ'],
      'Land Rover': [
        'Defender',
        'Discovery',
        'Discovery Sport',
        'Range Rover',
        'Range Rover Evoque',
        'Range Rover Sport',
        'Range Rover Velar'
      ],
      'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX'],
      'Mini': [
        'Clubman',
        'Convertible',
        'Countryman',
        'Hardtop 2 Door',
        'Hardtop 4 Door'
      ],
      'Smart': ['EQ fortwo'],
      'Dodge': ['Challenger', 'Charger', 'Durango', 'Grand Caravan', 'Journey'],
      'Chrysler': ['300', 'Pacifica', 'Voyager'],
      'Jeep': [
        'Cherokee',
        'Compass',
        'Gladiator',
        'Grand Cherokee',
        'Renegade',
        'Wrangler'
      ],
      'Ram': ['1500', '2500', '3500', 'ProMaster City'],
      'Fiat': ['124 Spider', '500', '500L', '500X'],
      'Alfa Romeo': ['4C', 'Giulia', 'Stelvio'],
      'Lamborghini': ['Aventador', 'Huracan', 'Urus'],
      'Maserati': ['Ghibli', 'GranTurismo', 'Levante', 'Quattroporte'],
      'Bentley': ['Bentayga', 'Continental', 'Flying Spur', 'Mulsanne'],
      'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Wraith'],
      'Genesis': ['G70', 'G80', 'G90'],
      'Buick': [
        'Enclave',
        'Encore',
        'Encore GX',
        'Envision',
        'LaCrosse',
        'Regal'
      ],
      'Cadillac': ['CT4', 'CT5', 'CT6', 'Escalade', 'XT4', 'XT5', 'XT6'],
      'Lincoln': ['Aviator', 'Corsair', 'MKZ', 'Nautilus', 'Navigator'],
      'GMC': [
        'Acadia',
        'Canyon',
        'Sierra 1500',
        'Sierra 2500HD',
        'Sierra 3500HD',
        'Terrain',
        'Yukon',
        'Yukon XL'
      ],
      'Aston Martin': ['DB11', 'DBS Superleggera', 'Vantage'],
      'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
      'Other': ['Other'],
    };
    return models;
  }
}
