name: eltracmo_staff
description: The staff app for the Eltracmo System
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  shared_preferences: ^2.0.18
  image_picker: ^0.8.7+1
  # flutter_local_notifications: ^13.0.0
  font_awesome_flutter: ^10.4.0
  # local_auth: ^2.1.6
  # mobile_scanner: ^3.0.0
  dio: ^5.0.2
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  intl: ^0.17.0
  cell_calendar: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/eltracmo_logo.png
    - assets/icons/appointment.png
    - assets/icons/car-wash.png
    - assets/icons/car.png
    - assets/icons/car-checklist.png
    - assets/icons/complain.png
    - assets/icons/maintenance_horiz.png
    - assets/icons/maintenance_vert.png
    - assets/icons/military-vehicle.png
    - assets/icons/profile.png
    - assets/icons/user-profile.png
